apiVersion: v1
kind: Service
metadata:
  name: student-app-service
spec:
  selector:
    app: student-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
    nodePort: 30001 # Specify a custom NodePort between 30000-32767
  type: NodePort
